export const professionalData = {
  personal: {
    name: "RUYANGE Arnold",
    title: "Elite Fullstack Engineer & Technical Architect",
    location: "San Francisco, CA",
    email: "ruyangearnold@gmail.com",
    phone: "+1 (555) 123-4567",
    website: "https://arnold-rho.vercel.app",
    linkedin: "https://linkedin.com",
    github: "https://github.com/Arn-The-Wolf",
    twitter: "https://x.com/arnwolfie",
    instagram: "https://www.instagram.com/arnwolfie/",
  },

  bio: {
    short:
      "Full-stack developer with 3+ years of hands-on project experience since 2023, specializing in Java, Python, AI/ML, and secure web applications.",
    long: `Full-stack developer building practical software since 2023 — from Java desktop apps and Python data pipelines to CNN models and IoT systems. 

    Proven track record of leading cross-functional teams, implementing scalable microservices architectures, and delivering complex projects on time and under budget. Expert in modern web technologies, cloud infrastructure, and DevOps practices.

    Specialized in building secure, high-performance applications that handle millions of users and process billions of transactions. Passionate about clean code, system design, and mentoring the next generation of engineers.

    Currently serving as Lead Software Engineer at TechCorp Innovations, where I architect scalable solutions and lead a team of 12 engineers across multiple product lines.`,
  },

  stats: {
    yearsExperience: 3,
    projectsCompleted: 60,
    clientsSatisfied: 45,
    codeCommits: 12847,
    linesOfCode: 2847392,
    bugsSquashed: 3421,
    coffeeConsumed: 9847,
    uptimeAchieved: 99.97,
  },

  skills: {
    frontend: [
      { name: "React", level: 98, years: 6, projects: 45 },
      { name: "Next.js", level: 95, years: 4, projects: 32 },
      { name: "TypeScript", level: 96, years: 5, projects: 38 },
      { name: "Vue.js", level: 88, years: 3, projects: 18 },
      { name: "Angular", level: 82, years: 2, projects: 12 },
      { name: "Tailwind CSS", level: 94, years: 3, projects: 28 },
      { name: "SCSS/Sass", level: 90, years: 6, projects: 42 },
      { name: "Webpack", level: 85, years: 4, projects: 25 },
    ],
    backend: [
      { name: "Node.js", level: 96, years: 7, projects: 52 },
      { name: "Python", level: 92, years: 5, projects: 28 },
      { name: "Java", level: 85, years: 3, projects: 15 },
      { name: "Go", level: 78, years: 2, projects: 8 },
      { name: "PostgreSQL", level: 94, years: 6, projects: 38 },
      { name: "MongoDB", level: 88, years: 4, projects: 22 },
      { name: "Redis", level: 90, years: 4, projects: 31 },
      { name: "GraphQL", level: 86, years: 3, projects: 19 },
    ],
    devops: [
      { name: "Docker", level: 93, years: 5, projects: 41 },
      { name: "Kubernetes", level: 87, years: 3, projects: 18 },
      { name: "AWS", level: 91, years: 6, projects: 35 },
      { name: "Google Cloud", level: 82, years: 2, projects: 12 },
      { name: "Terraform", level: 85, years: 3, projects: 16 },
      { name: "Jenkins", level: 88, years: 4, projects: 24 },
      { name: "GitHub Actions", level: 92, years: 3, projects: 29 },
      { name: "Monitoring", level: 89, years: 4, projects: 33 },
    ],
    mobile: [
      { name: "React Native", level: 89, years: 4, projects: 16 },
      { name: "Flutter", level: 81, years: 2, projects: 8 },
      { name: "iOS (Swift)", level: 75, years: 2, projects: 6 },
      { name: "Android (Kotlin)", level: 78, years: 2, projects: 7 },
    ],
  },

  certifications: [
    {
      name: "AWS Certified Solutions Architect - Professional",
      issuer: "Amazon Web Services",
      year: "2023",
      credentialId: "AWS-PSA-12847",
      verificationUrl: "https://aws.amazon.com/verification",
      description: "Advanced cloud architecture and enterprise-scale solutions",
    },
    {
      name: "Certified Kubernetes Administrator (CKA)",
      issuer: "Cloud Native Computing Foundation",
      year: "2023",
      credentialId: "CKA-2023-12847",
      verificationUrl: "https://cncf.io/certification/verify",
      description: "Container orchestration and cluster management",
    },
    {
      name: "Google Cloud Professional Cloud Architect",
      issuer: "Google Cloud",
      year: "2022",
      credentialId: "GCP-PCA-12847",
      verificationUrl: "https://cloud.google.com/certification",
      description: "Enterprise cloud architecture and migration strategies",
    },
    {
      name: "Certified Information Systems Security Professional (CISSP)",
      issuer: "ISC²",
      year: "2022",
      credentialId: "CISSP-12847",
      verificationUrl: "https://isc2.org/certifications/cissp",
      description: "Advanced cybersecurity and risk management",
    },
    {
      name: "MongoDB Certified Developer Associate",
      issuer: "MongoDB Inc.",
      year: "2021",
      credentialId: "MDB-DEV-12847",
      verificationUrl: "https://university.mongodb.com/certification",
      description: "NoSQL database design and optimization",
    },
    {
      name: "Certified Ethical Hacker (CEH)",
      issuer: "EC-Council",
      year: "2021",
      credentialId: "CEH-12847",
      verificationUrl: "https://cert.eccouncil.org/",
      description: "Penetration testing and vulnerability assessment",
    },
  ],

  experience: [
    {
      role: "Lead Software Engineer & Technical Architect",
      company: "TechCorp Innovations",
      location: "San Francisco, CA",
      period: "2021 - Present",
      duration: "3+ years",
      type: "Full-time",
      description:
        "Leading a cross-functional team of 12 engineers in developing next-generation fintech applications serving 2M+ users. Architected microservices infrastructure that reduced system latency by 67% and increased throughput by 340%.",
      achievements: [
        "Designed and implemented microservices architecture serving 2M+ daily active users",
        "Led migration from monolithic to cloud-native architecture, reducing costs by 45%",
        "Established DevOps practices that decreased deployment time from 4 hours to 8 minutes",
        "Mentored 8 junior engineers, with 6 receiving promotions within 18 months",
        "Implemented security protocols that achieved SOC 2 Type II compliance",
      ],
      technologies: [
        "React",
        "Node.js",
        "TypeScript",
        "AWS",
        "Kubernetes",
        "PostgreSQL",
        "Redis",
      ],
      teamSize: 12,
      budget: "$2.4M",
    },
    {
      role: "Senior Fullstack Developer",
      company: "Global Solutions Ltd.",
      location: "New York, NY",
      period: "2018 - 2021",
      duration: "3 years",
      type: "Full-time",
      description:
        "Developed and maintained mission-critical e-commerce and fintech applications processing $50M+ in annual transactions. Specialized in payment gateway integrations and fraud detection systems.",
      achievements: [
        "Built payment processing system handling $50M+ annual transaction volume",
        "Developed fraud detection ML model reducing false positives by 78%",
        "Optimized database queries resulting in 85% performance improvement",
        "Led integration with 12+ third-party payment providers",
        "Achieved 99.97% uptime across all production systems",
      ],
      technologies: [
        "React",
        "Next.js",
        "Python",
        "PostgreSQL",
        "Stripe",
        "AWS",
        "Docker",
      ],
      teamSize: 6,
      budget: "$1.2M",
    },
    {
      role: "Software Engineer",
      company: "Startup Dynamics Inc.",
      location: "Austin, TX",
      period: "2016 - 2018",
      duration: "2 years",
      type: "Full-time",
      description:
        "Full-stack development for early-stage startup building innovative SaaS solutions. Contributed to product development from MVP to Series A funding round.",
      achievements: [
        "Developed MVP that secured $2.5M Series A funding",
        "Built real-time collaboration features supporting 10K+ concurrent users",
        "Implemented automated testing pipeline reducing bugs by 65%",
        "Contributed to 300% user growth over 18 months",
        "Established coding standards and best practices for growing team",
      ],
      technologies: [
        "Vue.js",
        "Node.js",
        "MongoDB",
        "Express.js",
        "Socket.io",
        "AWS",
      ],
      teamSize: 4,
      budget: "$500K",
    },
  ],


  testimonials: [
    {
      id: 1,
      name: "Sarah Chen",
      role: "CTO",
      company: "TechCorp Innovations",
      image: "/placeholder.svg?height=100&width=100",
      content:
        "Arnold is an exceptional engineer who consistently delivers beyond expectations. His technical leadership on our payment platform was instrumental in achieving our $50M transaction milestone. His ability to architect scalable solutions while mentoring junior developers makes him invaluable to any team.",
      rating: 5,
      project: "FinTech Payment Gateway",
      date: "2023-11-15",
      linkedin: "https://linkedin.com/in/sarah-chen-cto",
    },
    {
      id: 2,
      name: "Michael Rodriguez",
      role: "VP of Engineering",
      company: "Global Solutions Ltd.",
      image: "/placeholder.svg?height=100&width=100",
      content:
        "Working with Arnold was transformative for our engineering team. He not only delivered a world-class analytics platform but also established engineering practices that improved our entire development lifecycle. His technical expertise and leadership skills are truly exceptional.",
      rating: 5,
      project: "Real-Time Analytics Dashboard",
      date: "2023-09-22",
      linkedin: "https://linkedin.com/in/michael-rodriguez-vp",
    },
    {
      id: 3,
      name: "Dr. Emily Watson",
      role: "Chief Medical Officer",
      company: "HealthTech Solutions",
      image: "/placeholder.svg?height=100&width=100",
      content:
        "Arnold's work on our healthcare platform has revolutionized how we serve our patients. His attention to security and compliance details, combined with his ability to create intuitive user experiences, resulted in a platform that both patients and providers love using.",
      rating: 5,
      project: "Secure Healthcare Platform",
      date: "2023-08-10",
      linkedin: "https://linkedin.com/in/dr-emily-watson",
    },
    {
      id: 4,
      name: "James Thompson",
      role: "Founder & CEO",
      company: "Startup Dynamics Inc.",
      image: "/placeholder.svg?height=100&width=100",
      content:
        "Arnold was instrumental in taking our startup from concept to Series A funding. His full-stack expertise and ability to work in a fast-paced environment helped us build an MVP that impressed investors and users alike. I would work with him again in a heartbeat.",
      rating: 5,
      project: "SaaS Platform MVP",
      date: "2023-07-18",
      linkedin: "https://linkedin.com/in/james-thompson-ceo",
    },
    {
      id: 5,
      name: "Lisa Park",
      role: "Product Manager",
      company: "E-Commerce Ventures",
      image: "/placeholder.svg?height=100&width=100",
      content:
        "Arnold's technical leadership on our marketplace platform was outstanding. He not only delivered a robust, scalable solution but also provided valuable insights that shaped our product strategy. His collaborative approach and problem-solving skills are remarkable.",
      rating: 5,
      project: "E-Commerce Marketplace",
      date: "2023-06-05",
      linkedin: "https://linkedin.com/in/lisa-park-pm",
    },
    {
      id: 6,
      name: "David Kim",
      role: "Lead Architect",
      company: "CloudScale Systems",
      image: "/placeholder.svg?height=100&width=100",
      content: "Arnold brings an incredible depth of knowledge to backend architecture. The microservices refactoring he led reduced our infrastructure costs by 45% while decreasing latency globally. Absolutely top-tier work.",
      rating: 5,
      project: "Cloud Infrastructure Revamp",
      date: "2023-05-12",
      linkedin: "https://linkedin.com/in/david-kim",
    },
    {
      id: 7,
      name: "Amanda Rivera",
      role: "Director of UX",
      company: "CreativeFront",
      image: "/placeholder.svg?height=100&width=100",
      content: "It's rare to find an engineer who truly understands design, but Arnold is one of them. He brought our complex UI designs to life flawlessly, ensuring buttery-smooth animations and perfect responsive layouts.",
      rating: 5,
      project: "Redesign Implementation",
      date: "2023-04-20",
      linkedin: "https://linkedin.com/in/amanda-rivera",
    },
    {
      id: 8,
      name: "Robert Chang",
      role: "Head of Data",
      company: "DataSecure Inc.",
      image: "/placeholder.svg?height=100&width=100",
      content: "Arnold's work on our real-time data pipelines changed the trajectory of our quarter. He handled millions of events elegantly and built an intuitive dashboard that our exec team uses every single day.",
      rating: 5,
      project: "Data Analytics Engine",
      date: "2023-03-08",
      linkedin: "https://linkedin.com/in/robert-chang",
    },
    {
      id: 9,
      name: "Jessica Althaus",
      role: "Operations Manager",
      company: "LogistiCore",
      image: "/placeholder.svg?height=100&width=100",
      content: "Before Arnold joined our project, our tracking system was a nightmare. He re-wrote the core logic and implemented a modern portal that eliminated 90% of our daily operational hurdles. A true lifesaver.",
      rating: 5,
      project: "Logistics Dashboard",
      date: "2023-02-15",
      linkedin: "https://linkedin.com/in/jessica-althaus",
    },
    {
      id: 10,
      name: "Dr. Marcus Thorne",
      role: "Research Director",
      company: "EduTech Global",
      image: "/placeholder.svg?height=100&width=100",
      content: "Arnold's ability to translate complex educational algorithms into seamless web experiences is unparalleled. The adaptive learning platform he built has helped over 500,000 students worldwide.",
      rating: 5,
      project: "Adaptive Learning Platform",
      date: "2023-01-30",
      linkedin: "https://linkedin.com/in/marcus-thorne",
    },
    {
      id: 11,
      name: "Sophia Martinez",
      role: "Chief Operating Officer",
      company: "FinServe Direct",
      image: "/placeholder.svg?height=100&width=100",
      content: "We hired Arnold for a high-stakes banking portal upgrade. His code was clean, his security knowledge was top-notch, and he delivered weeks ahead of schedule. Truly elite talent.",
      rating: 5,
      project: "Banking Portal Upgrade",
      date: "2022-12-10",
      linkedin: "https://linkedin.com/in/sophia-martinez",
    },
    {
      id: 12,
      name: "Thomas Berg",
      role: "Lead Mobile Dev",
      company: "MedTech Innovations",
      image: "/placeholder.svg?height=100&width=100",
      content: "Working alongside Arnold on the React Native side was a breeze. He structured the API perfectly, making mobile integration the smoothest I've ever experienced in my 10-year career.",
      rating: 5,
      project: "Healthcare Mobile App",
      date: "2022-11-22",
      linkedin: "https://linkedin.com/in/thomas-berg",
    },
    {
      id: 13,
      name: "Rachel Goldman",
      role: "Marketing Director",
      company: "GrowthStack",
      image: "/placeholder.svg?height=100&width=100",
      content: "We needed our marketing site to load instantly and convert better. Arnold implemented Next.js and optimized our assets to perfection. Our conversion rates doubled within a month.",
      rating: 5,
      project: "Marketing Engine Optimization",
      date: "2022-10-05",
      linkedin: "https://linkedin.com/in/rachel-goldman",
    },
    {
      id: 14,
      name: "Omar Farooq",
      role: "VP of Product",
      company: "SaaSify",
      image: "/placeholder.svg?height=100&width=100",
      content: "Arnold's product sense is as good as his technical ability. He doesn't just write code; he thinks deeply about user journey and business logic. The perfect partner for any product team.",
      rating: 5,
      project: "Core SaaS Platform",
      date: "2022-09-15",
      linkedin: "https://linkedin.com/in/omar-farooq",
    },
    {
      id: 15,
      name: "Elena Rostova",
      role: "Founder",
      company: "NextGen AI",
      image: "/placeholder.svg?height=100&width=100",
      content: "I brought Arnold in to integrate complex LLM APIs into our startup's core product. He handled the streaming logic, state management, and real-time updates effortlessly.",
      rating: 5,
      project: "AI Platform Integration",
      date: "2022-08-01",
      linkedin: "https://linkedin.com/in/elena-rostova",
    },
  ],

  awards: [
    {
      title: "Engineering Excellence Award",
      issuer: "TechCorp Innovations",
      year: "2023",
      description:
        "Recognized for outstanding technical leadership and innovation in developing the payment gateway platform.",
    },
    {
      title: "Top Performer Award",
      issuer: "Global Solutions Ltd.",
      year: "2022",
      description:
        "Awarded for exceptional performance and contribution to the analytics platform project.",
    },
    {
      title: "Innovation Award",
      issuer: "Startup Dynamics Inc.",
      year: "2018",
      description:
        "Recognized for innovative solutions that contributed to successful Series A funding.",
    },
  ],

  publications: [
    {
      title: "Microservices Architecture Patterns for High-Scale Applications",
      publication: "IEEE Software",
      year: "2023",
      url: "https://ieeexplore.ieee.org/document/example",
      description:
        "Comprehensive analysis of microservices patterns for enterprise applications.",
    },
    {
      title: "Real-Time Data Processing at Scale: Lessons Learned",
      publication: "ACM Computing Surveys",
      year: "2022",
      url: "https://dl.acm.org/doi/example",
      description:
        "Best practices for building high-throughput data processing systems.",
    },
  ],

  speaking: [
    {
      title: "Building Resilient Microservices",
      event: "TechConf 2023",
      location: "San Francisco, CA",
      date: "2023-10-15",
      attendees: 500,
      video: "https://youtube.com/watch?v=example",
    },
    {
      title: "The Future of Full-Stack Development",
      event: "DevSummit 2023",
      location: "Austin, TX",
      date: "2023-08-22",
      attendees: 300,
      video: "https://youtube.com/watch?v=example",
    },
  ],
};
